//
//  FeedListRouter.swift
//  Feed
//
//  Created by Antonov Vladislav on 20/11/2019.
//  Copyright (c) 2019 Antonov Vladislav. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol FeedListRoutingLogic: class {
	func openBookDetails(url: URL)
}

protocol FeedListDataPassing {
	var dataStore: FeedListDataStore? { get }
}

final class FeedListRouter: FeedListRoutingLogic, FeedListDataPassing {
	weak var viewController: FeedListViewController?
	var dataStore: FeedListDataStore?

	// MARK: Navigation
	func openBookDetails(url: URL) {
		UIApplication.shared.open(url, options: [:], completionHandler: nil)
	}
}
